[metadata]
name = djangoldp_data_food_consortium
version = attr: data_food_consortium.__version__
description = DjangoLDP package for Data Food Consortium proxies
long_description = file: README.md
author = StartinBlox
author_email = calum@startinblox.com
license = MIT
classifiers =
    Programming Language :: Python :: 3

[options]
packages = find:
install_requires =
    djangoldp>=4.0.7
    djangoldp_csv
    rdflib~=7.1
include_package_data = true

[semantic_release]
version_source = tag
version_variable = data_food_consortium/__init__.py:__version__
commit_parser = commit_parser.parse
