# Generated by Django 4.2.20 on 2025-04-24 14:17

from django.db import migrations, models
import djangoldp.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                (
                    "email",
                    djangoldp.fields.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "logo",
                    djangoldp.fields.LDPUrlField(blank=True, max_length=255, null=True),
                ),
                (
                    "enterpriseid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, help_text="Unique Id of the Enterprise", null=True
                    ),
                ),
                (
                    "VATnumber",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="Any Tax Registration Number that is applicable to the Enterprise, in the jurisdiction the Enterprise is operating in.",
                        null=True,
                    ),
                ),
                (
                    "VATstatus",
                    djangoldp.fields.BooleanField(
                        default=False,
                        help_text="Indicates whether the Enterprise charges VAT or not",
                        null=True,
                    ),
                ),
            ],
            options={
                "rdf_type": "dfc-b:Enterprise",
            },
        ),
    ]
