# Generated by Django 4.2.20 on 2025-04-24 22:28

from django.db import migrations, models
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_food_consortium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'default_permissions': {'control', 'view', 'delete', 'add', 'change'}},
        ),
        migrations.AddField(
            model_name='enterprise',
            name='contact_name',
            field=djangoldp.fields.TextField(blank=True, help_text='Name of the primary contact (from the OFN ontology)', null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='description',
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='logo_url',
            field=djangoldp.fields.LDPUrlField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='long_description',
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='name',
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='phone_number',
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='promo_image_url',
            field=djangoldp.fields.LDPUrlField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, db_index=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('name', djangoldp.fields.TextField(blank=True, null=True)),
                ('url', djangoldp.fields.LDPUrlField(blank=True, null=True)),
                ('enterprise', djangoldp.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='data_food_consortium.enterprise')),
            ],
            options={
                'abstract': False,
                'default_permissions': {'control', 'view', 'delete', 'add', 'change'},
                'rdf_type': 'dfc-b:SocialMedia',
                'depth': 0,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, db_index=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('email', djangoldp.fields.EmailField(blank=True, max_length=254, null=True)),
                ('logo', djangoldp.fields.LDPUrlField(blank=True, max_length=255, null=True)),
                ('logo_url', djangoldp.fields.LDPUrlField(blank=True, max_length=255, null=True)),
                ('promo_image_url', djangoldp.fields.LDPUrlField(blank=True, max_length=255, null=True)),
                ('phone_number', djangoldp.fields.TextField(blank=True, null=True)),
                ('first_name', djangoldp.fields.TextField(blank=True, null=True)),
                ('last_name', djangoldp.fields.TextField(blank=True, null=True)),
                ('affiliated_to', djangoldp.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliates', to='data_food_consortium.enterprise')),
            ],
            options={
                'rdf_type': 'dfc-b:Person',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, db_index=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('city', djangoldp.fields.TextField(blank=True, null=True)),
                ('country', djangoldp.fields.TextField(blank=True, null=True)),
                ('latitude', djangoldp.fields.TextField(blank=True, null=True)),
                ('longitude', djangoldp.fields.TextField(blank=True, null=True)),
                ('postcode', djangoldp.fields.TextField(blank=True, null=True)),
                ('region', djangoldp.fields.TextField(blank=True, null=True)),
                ('street', djangoldp.fields.TextField(blank=True, null=True)),
                ('address_of', djangoldp.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='data_food_consortium.enterprise')),
            ],
            options={
                'abstract': False,
                'default_permissions': {'control', 'view', 'delete', 'add', 'change'},
                'rdf_type': 'dfc-b:Address',
                'depth': 0,
            },
        ),
    ]
