# Generated by Django 4.2.20 on 2025-05-08 14:38

from django.db import migrations
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_food_consortium', '0002_alter_enterprise_options_enterprise_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseaddress',
            name='address_of',
            field=djangoldp.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='data_food_consortium.enterprise'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='enterprise',
            field=djangoldp.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='data_food_consortium.enterprise'),
        ),
    ]
