# Generated by Django 4.2.20 on 2025-05-14 10:00

from django.db import migrations, models
import django.utils.timezone
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0003_alter_enterpriseaddress_address_of_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enterprise",
            name="data_server_source",
            field=djangoldp.fields.TextField(
                default="http://localhost:8000/",
                help_text="The URL of the dataserver which provided the instance",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enterprise",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="enterpriseaddress",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enterpriseaddress",
            name="data_server_source",
            field=djangoldp.fields.TextField(
                default="http://localhost:8000/",
                help_text="The URL of the dataserver which provided the instance",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enterpriseaddress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="data_server_source",
            field=djangoldp.fields.TextField(
                default="http://localhost:8000/",
                help_text="The URL of the dataserver which provided the instance",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="data_server_source",
            field=djangoldp.fields.TextField(
                default="http://localhost:8000/",
                help_text="The URL of the dataserver which provided the instance",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
