# Generated by Django 4.2.20 on 2025-06-17 09:39

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0005_suppliedproduct_suppliedproductgroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="data_server_source",
            field=djangoldp.fields.TextField(
                blank=True,
                help_text="The URL of the dataserver which provided the instance",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterpriseaddress",
            name="data_server_source",
            field=djangoldp.fields.TextField(
                blank=True,
                help_text="The URL of the dataserver which provided the instance",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localizedproduct",
            name="data_server_source",
            field=djangoldp.fields.TextField(
                blank=True,
                help_text="The URL of the dataserver which provided the instance",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="data_server_source",
            field=djangoldp.fields.TextField(
                blank=True,
                help_text="The URL of the dataserver which provided the instance",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="data_server_source",
            field=djangoldp.fields.TextField(
                blank=True,
                help_text="The URL of the dataserver which provided the instance",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="suppliedproduct",
            name="data_server_source",
            field=djangoldp.fields.TextField(
                blank=True,
                help_text="The URL of the dataserver which provided the instance",
                null=True,
            ),
        ),
    ]
