# Generated by Django 4.2.20 on 2025-07-16 08:38

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0006_alter_enterprise_data_server_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="proxy_of",
            field=djangoldp.fields.LDPUrlField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enterpriseaddress",
            name="proxy_of",
            field=djangoldp.fields.LDPUrlField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="localizedproduct",
            name="proxy_of",
            field=djangoldp.fields.LDPUrlField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="proxy_of",
            field=djangoldp.fields.LDPUrlField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="proxy_of",
            field=djangoldp.fields.LDPUrlField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suppliedproduct",
            name="proxy_of",
            field=djangoldp.fields.LDPUrlField(blank=True, null=True),
        ),
    ]
