# Generated by Django 4.2.20 on 2025-07-24 11:58

from django.db import migrations
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_food_consortium",
            "0007_enterprise_proxy_of_enterpriseaddress_proxy_of_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="affiliated_to",
        ),
        migrations.AddField(
            model_name="person",
            name="affiliates",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="affiliated_to",
                to="data_food_consortium.enterprise",
            ),
        ),
    ]
