# Generated by Django 4.2.20 on 2025-08-07 18:09

from django.db import migrations, models
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0008_remove_person_affiliated_to_person_affiliates"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_server_source",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The URL of the dataserver which provided the instance",
                        null=True,
                    ),
                ),
                ("proxy_of", djangoldp.fields.LDPUrlField(blank=True, null=True)),
                (
                    "extra_availability_time",
                    djangoldp.fields.TextField(blank=True, null=True),
                ),
                (
                    "extra_delivery_condition",
                    djangoldp.fields.TextField(blank=True, null=True),
                ),
                ("sku", djangoldp.fields.TextField(blank=True, null=True)),
                (
                    "stock_limitation",
                    djangoldp.fields.FloatField(blank=True, null=True),
                ),
                (
                    "managed_by",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalog_items",
                        to="data_food_consortium.enterprise",
                    ),
                ),
                (
                    "references",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalog_items",
                        to="data_food_consortium.suppliedproduct",
                    ),
                ),
            ],
            options={
                "rdf_type": "dfc-b:CatalogItem",
                "serializer_fields": [
                    "@id",
                    "managed_by",
                    "references",
                    "extra_availability_time",
                    "extra_delivery_condition",
                    "sku",
                    "stock_limitation",
                    "offers",
                ],
                "nested_fields": ["offers"],
            },
        ),
        migrations.CreateModel(
            name="CustomerCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_server_source",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The URL of the dataserver which provided the instance",
                        null=True,
                    ),
                ),
                ("proxy_of", djangoldp.fields.LDPUrlField(blank=True, null=True)),
                (
                    "defined_by",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_categories",
                        to="data_food_consortium.enterprise",
                    ),
                ),
            ],
            options={
                "rdf_type": "dfc-b:CustomerCategory",
                "serializer_fields": [
                    "@id",
                    "managed_by",
                    "references",
                    "extra_availability_time",
                    "extra_delivery_condition",
                    "sku",
                    "offers",
                ],
                "nested_fields": ["offers"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_server_source",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The URL of the dataserver which provided the instance",
                        null=True,
                    ),
                ),
                ("proxy_of", djangoldp.fields.LDPUrlField(blank=True, null=True)),
                ("value", djangoldp.fields.FloatField(blank=True, null=True)),
                ("has_unit", djangoldp.fields.TextField(blank=True, null=True)),
            ],
            options={
                "rdf_type": "dfc-b:Price",
                "serializer_fields": ["@id", "value", "has_unit"],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_server_source",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The URL of the dataserver which provided the instance",
                        null=True,
                    ),
                ),
                ("proxy_of", djangoldp.fields.LDPUrlField(blank=True, null=True)),
                (
                    "offered_for",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="offers",
                        to="data_food_consortium.price",
                    ),
                ),
                (
                    "offered_to",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="data_food_consortium.customercategory",
                    ),
                ),
                (
                    "offers",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="data_food_consortium.catalogitem",
                    ),
                ),
            ],
            options={
                "rdf_type": "dfc-b:Offer",
                "serializer_fields": ["@id", "offers", "offered_to", "offered_for"],
            },
        ),
    ]
