# Generated by Django 4.2.20 on 2025-08-12 14:51

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0009_catalogitem_customercategory_price_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliedproduct",
            name="has_ingredient",
            field=djangoldp.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="suppliedproduct",
            name="specific_condition",
            field=djangoldp.fields.TextField(
                blank=True,
                help_text="Any specific conditions requried for storage or carriage of the Product.",
                null=True,
            ),
        ),
    ]
