# Generated by Django 4.2.21 on 2025-08-18 11:29

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0009_catalogitem_customercategory_price_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="website_page",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="website_page",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="logo",
            field=djangoldp.fields.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="logo_url",
            field=djangoldp.fields.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="promo_image_url",
            field=djangoldp.fields.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="logo",
            field=djangoldp.fields.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="logo_url",
            field=djangoldp.fields.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="promo_image_url",
            field=djangoldp.fields.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="url",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="suppliedproduct",
            name="has_type",
            field=djangoldp.fields.CharField(
                blank=True,
                choices=[
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#alcoholic-beverage",
                        "Alcoholic beverage",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#almond",
                        "Almond",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#aperitif",
                        "Aperitif",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#apples",
                        "Apples",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#apricot",
                        "Apricot",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#aromatic",
                        "Aromatic",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#artichoke",
                        "Artichoke",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#asparagus",
                        "Asparagus",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#bakery",
                        "Bakery",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#basil",
                        "Basil",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#bean",
                        "Bean",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#beans",
                        "Beans",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#beef",
                        "Beef",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#beer",
                        "Beer",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#beetroot",
                        "Beetroot",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#berry",
                        "Berry",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#biscuit",
                        "Biscuit",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#blackberry",
                        "Blackberry",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#blackcurrant",
                        "Blackcurrant",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#blueberry",
                        "Blueberry",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#bluefoot-mushroom",
                        "Bluefoot mushroom",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#bottled-fruit",
                        "Bottled fruit",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#bottled-vegetable",
                        "Bottled vegetable",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#bread",
                        "Bread",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#broccoli-cabbage",
                        "Broccoli cabbage",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#brussels-sprouts",
                        "Brussels sprouts",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#butter",
                        "Butter",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#butternut",
                        "Butternut",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#cabbage",
                        "Cabbage",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#canned-fruit",
                        "Canned fruit",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#canned-vegetable",
                        "Canned vegetable",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#carrot",
                        "Carrot",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#cauliflower",
                        "Cauliflower",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#celeriac",
                        "Celeriac",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#celery-branch",
                        "Celery branch",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#chanterelle-mushroom",
                        "Chanterelle mushroom",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#chard",
                        "Chard",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#cherry",
                        "Cherry",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#cherry-tomato",
                        "Cherry tomato",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#chervil",
                        "Chervil",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#chestnut",
                        "Chestnut",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#chewed-up",
                        "Chewed up",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#chicken",
                        "Chicken",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#chicory",
                        "Chicory",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#chilli-pepper",
                        "Chilli pepper",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#chinese-cabbage",
                        "Chinese cabbage",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#chive",
                        "Chive",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#cider",
                        "Cider",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#clementine",
                        "Clementine",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#cluster-tomato",
                        "Cluster tomato",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#confectionery",
                        "Confectionery",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#cooked-meat",
                        "Cooked meat",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#coriander",
                        "Coriander",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#corn-salad",
                        "Corn salad",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#cosmetic",
                        "Cosmetic",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#coulemelle-mushroom",
                        "Coulemelle mushroom",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#courgette",
                        "Courgette",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#cow-dairy-product",
                        "Cow dairy product",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#cream-cheese",
                        "Cream cheese",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#crepe-and-galette",
                        "Crepe and galette",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#cress",
                        "Cress",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#cucumber",
                        "Cucumber",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#currant",
                        "Currant",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#dairy-dessert",
                        "Dairy dessert",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#dairy-product",
                        "Dairy product",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#dandelion",
                        "Dandelion",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#deaths-trumpet",
                        "Deaths trumpet",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#delicatessen",
                        "Delicatessen",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#digestive",
                        "Digestive",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#dill",
                        "Dill",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#dried-fruit",
                        "Dried fruit",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#dried-vegetable",
                        "Dried vegetable",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#dried_herb",
                        "Dried_herb",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#dried_goods",
                        "Dried goods",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#drink",
                        "Drink",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#duck",
                        "Duck",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#egg",
                        "Egg",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#eggplant",
                        "Eggplant",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#endive",
                        "Endive",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#fennel",
                        "Fennel",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#festive-poultry",
                        "Festive poultry",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#fifth-range-vegetable",
                        "Fifth range vegetable",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#fig",
                        "Fig",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#fish",
                        "Fish",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#fishery-product",
                        "Fishery product",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#flake",
                        "Flake",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#flavored-yogurt",
                        "Flavored yogurt",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#flour",
                        "Flour",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#flower",
                        "Flower",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#fourth-range-vegetable",
                        "Fourth range vegetable",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#fresh-cheese",
                        "Fresh cheese",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#fresh-cream",
                        "Fresh cream",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#fresh-meat",
                        "Fresh meat",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#frozen",
                        "Frozen",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#frozen-fruit",
                        "Frozen fruit",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#frozen-meal",
                        "Frozen meal",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#frozen-meat",
                        "Frozen meat",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#frozen-vegetable",
                        "Frozen vegetable",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#fruit",
                        "Fruit",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#fruit-in-compote",
                        "Fruit in compote",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#fruit-juice",
                        "Fruit juice",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#garlic",
                        "Garlic",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#girolle-mushroom",
                        "Girolle mushroom",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#goat-dairy-dessert",
                        "Goat dairy dessert",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#goat-dairy-product",
                        "Goat dairy product",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#goat-flavored-yogurt",
                        "Goat flavored yogurt",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#goat-fresh-cheese",
                        "Goat fresh cheese",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#goat-mature-cheese",
                        "Goat mature cheese",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#goat-milk",
                        "Goat milk",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#goat-natural-yogurt",
                        "Goat natural yogurt",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#goat-sweet-yogurt",
                        "Goat sweet yogurt",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#goat-yogurt-on-a-bed-of-fruit",
                        "Goat yogurt on a bed of fruit",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#goat-yogurt-with-fruits",
                        "Goat yogurt with fruits",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#goose",
                        "Goose",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#gooseberry",
                        "Gooseberry",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#grain",
                        "Grain",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#grape",
                        "Grape",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#green-garlic",
                        "Green garlic",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#grilling-meat",
                        "Grilling meat",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#guinea-fowl",
                        "Guinea fowl",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#hazelnut",
                        "Hazelnut",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#herb",
                        "Herb",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#hierloom-squash",
                        "Hierloom squash",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#hierloom-tomato",
                        "Hierloom tomato",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#honey",
                        "Honey",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#inedible",
                        "Inedible",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#jam",
                        "Jam",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#jerusalem-artichoke",
                        "Jerusalem artichoke",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#kale",
                        "Kale",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#kale-cabbage",
                        "Kale cabbage",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#kiwi",
                        "Kiwi",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#kohlrabi",
                        "Kohlrabi",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#lamb",
                        "Lamb",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#laurel",
                        "Laurel",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#leek",
                        "Leek",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#lemon",
                        "Lemon",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#lemonade",
                        "Lemonade",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#lentils",
                        "Lentils",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#lettuce",
                        "Lettuce",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#local-grocery-store",
                        "Local grocery store",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#mandarin",
                        "Mandarin",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#mature-cheese",
                        "Mature cheese",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#meat-product",
                        "Meat product",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#medlar",
                        "Medlar",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#melon",
                        "Melon",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#mesclun",
                        "Mesclun",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#milk",
                        "Milk",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#milky-mushroom",
                        "Milky mushroom",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#mint",
                        "Mint",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#morel",
                        "Morel",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#mousseron",
                        "Mousseron",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#mushroom",
                        "Mushroom",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#natural-yogurt",
                        "Natural yogurt",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#nectarine",
                        "Nectarine",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#non-local-fruit",
                        "Non local fruit",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#non-local-vegetable",
                        "Non local vegetable",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#nut",
                        "Nut",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#oil",
                        "Oil",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#old-variety-tomato",
                        "Old variety tomato",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#onion",
                        "Onion",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#orange",
                        "Orange",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#other-cheese",
                        "Other cheese",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#other-dairy-product",
                        "Other dairy product",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#other-milk",
                        "Other milk",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#oyster-mushroom",
                        "Oyster mushroom",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#paris-mushroom",
                        "Paris mushroom",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#parsley",
                        "Parsley",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#parsnip",
                        "Parsnip",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#pasta",
                        "Pasta",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#pastry",
                        "Pastry",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#pattypan-squash",
                        "Pattypan squash",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#peach",
                        "Peach",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#pear",
                        "Pear",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#peas",
                        "Peas",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#pepper",
                        "Pepper",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#pie-pastry",
                        "Pie pastry",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#pigeon",
                        "Pigeon",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#plant",
                        "Plant",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#plum",
                        "Plum",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#porcini",
                        "Porcini",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#pork",
                        "Pork",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#potato",
                        "Potato",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#poultry",
                        "Poultry",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#processed-fruit",
                        "Processed fruit",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#processed-vegetable",
                        "Processed vegetable",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#prune",
                        "Prune",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#pumpkin",
                        "Pumpkin",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#quail",
                        "Quail",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#quince",
                        "Quince",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#quinoa",
                        "Quinoa",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#rabbit",
                        "Rabbit",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#radish",
                        "Radish",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#raspberry",
                        "Raspberry",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#ready-meal",
                        "Ready meal",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#red-cabbage",
                        "Red cabbage",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#rhubarb",
                        "Rhubarb",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#rice",
                        "Rice",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#rocket",
                        "Rocket",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#romanesco",
                        "Romanesco",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#rosemary",
                        "Rosemary",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#round-tomato",
                        "Round tomato",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#rutabaga",
                        "Rutabaga",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sage",
                        "Sage",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#salad",
                        "Salad",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#salad-mix",
                        "Salad mix",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#salsify",
                        "Salsify",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#salt",
                        "Salt",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#salting",
                        "Salting",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#savory-groceries",
                        "Savory groceries",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#savoy-cabbage",
                        "Savoy cabbage",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#seashell",
                        "Seashell",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#seed",
                        "Seed",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#semolina",
                        "Semolina",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#shallot",
                        "Shallot",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sheep-dairy-dessert",
                        "Sheep dairy dessert",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sheep-dairy-product",
                        "Sheep dairy product",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sheep-flavored-yogurt",
                        "Sheep flavored yogurt",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sheep-fresh-cheese",
                        "Sheep fresh cheese",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sheep-mature-cheese",
                        "Sheep mature cheese",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sheep-milk",
                        "Sheep milk",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sheep-natural-yogurt",
                        "Sheep natural yogurt",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sheep-sweet-yogurt",
                        "Sheep sweet yogurt",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sheep-yogurt-on-a-bed-of-fruit",
                        "Sheep yogurt on a bed of fruit",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sheep-yogurt-with-fruits",
                        "Sheep yogurt with fruits",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sheepfoot-mushroom",
                        "Sheepfoot mushroom",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#shellfish",
                        "Shellfish",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#simmering-meat",
                        "Simmering meat",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#smooth-cabbage",
                        "Smooth cabbage",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#smoothie",
                        "Smoothie",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#snails",
                        "Snails",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#soft-drink",
                        "Soft drink",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#soup",
                        "Soup",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#spinach",
                        "Spinach",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#squash",
                        "Squash",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#strawberry",
                        "Strawberry",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sweet-groceries",
                        "Sweet groceries",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#sweet-yogurt",
                        "Sweet yogurt",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#tarragon",
                        "Tarragon",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#thyme",
                        "Thyme",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#tomato",
                        "Tomato",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#truffle",
                        "Truffle",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#turkey",
                        "Turkey",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#turnip",
                        "Turnip",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#uchiki-kuri-squash",
                        "Uchiki kuri squash",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#veal",
                        "Veal",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#vegetable",
                        "Vegetable",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#viennoiserie-",
                        "Viennoiserie ",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#walnut",
                        "Walnut",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#wine",
                        "Wine",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#yam",
                        "Yam",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#yogurt-on-a-bed-of-fruit",
                        "Yogurt on a bed of fruit",
                    ),
                    (
                        "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/productTypes.rdf#yogurt-with-fruits",
                        "Yogurt with fruits",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="has_type",
            ),
        ),
        migrations.AlterField(
            model_name="suppliedproduct",
            name="url",
            field=djangoldp.fields.TextField(blank=True, max_length=255, null=True),
        ),
    ]
