# Generated by Django 4.2.20 on 2025-08-24 10:32

from django.db import migrations
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0010_suppliedproduct_has_ingredient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogitem",
            name="references",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referenced_by",
                to="data_food_consortium.suppliedproduct",
            ),
        ),
    ]
