# Generated by Django 4.2.21 on 2025-08-18 12:26

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_food_consortium",
            "0010_enterprise_website_page_person_website_page_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliedproduct",
            name="image",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
    ]
