# Generated by Django 4.2.21 on 2025-08-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0010_suppliedproduct_has_ingredient_and_more"),
        ("data_food_consortium", "0011_suppliedproduct_image"),
    ]

    operations = []
