# Generated by Django 4.2.21 on 2025-08-18 12:32

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0012_merge_20250818_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliedproduct",
            name="has_ingredient",
            field=djangoldp.fields.JSONField(blank=True, null=True),
        ),
    ]
