# Generated by Django 4.2.20 on 2025-08-12 14:51

from django.db import migrations
from django.db import models
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0013_alter_suppliedproduct_has_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliedproduct",
            name="specific_condition",
            field=djangoldp.fields.TextField(
                blank=True,
                help_text="Any specific conditions requried for storage or carriage of the Product.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="references",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="referenced_by",
                to="data_food_consortium.suppliedproduct",
            ),
        ),
    ]
