# Generated by Django 4.2.20 on 2025-08-24 14:59

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0014_suppliedproduct_has_ingredient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="email",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
    ]
