# Generated by Django 4.2.20 on 2025-08-26 08:55

from django.db import migrations, models
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0015_alter_enterprise_email_alter_person_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_server_source",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The URL of the dataserver which provided the instance",
                        null=True,
                    ),
                ),
                ("proxy_of", djangoldp.fields.LDPUrlField(blank=True, null=True)),
                ("name", djangoldp.fields.TextField(blank=True, null=True)),
            ],
            options={
                "rdf_type": "cqcm:Service",
                "serializer_fields": [
                    "@id",
                    "created_at",
                    "updated_at",
                    "name",
                    "suppliers",
                ],
                "nested_fields": ["suppliers"],
            },
        ),
        migrations.CreateModel(
            name="EnterpriseService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_server_source",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The URL of the dataserver which provided the instance",
                        null=True,
                    ),
                ),
                ("proxy_of", djangoldp.fields.LDPUrlField(blank=True, null=True)),
                (
                    "enterprise",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="data_food_consortium.enterprise",
                    ),
                ),
                (
                    "service",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="suppliers",
                        to="data_food_consortium.service",
                    ),
                ),
            ],
            options={
                "rdf_type": "cqcm:EnterpriseService",
                "container_path": "enterprise_services",
                "serializer_fields": [
                    "@id",
                    "created_at",
                    "updated_at",
                    "enterprise",
                    "service",
                ],
            },
        ),
    ]
