# Generated by Django 4.2.20 on 2025-08-26 13:51

from django.db import migrations, models
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0016_service_enterpriseservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordination",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_server_source",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The URL of the dataserver which provided the instance",
                        null=True,
                    ),
                ),
                ("proxy_of", djangoldp.fields.LDPUrlField(blank=True, null=True)),
                ("name", djangoldp.fields.TextField(blank=True, null=True)),
                (
                    "margin_percent",
                    djangoldp.fields.FloatField(
                        blank=True,
                        default=0.0,
                        help_text="The percentage margin the coordinating Enterprise is charging as comission for managing the Sales Session (from 0-100)",
                        null=True,
                    ),
                ),
                (
                    "enterprise",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        help_text="Confirms the Enterprise Coordinates certain SaleSessions, and defines margin percentage that the Enterprise takes for managing the SaleSession",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinations",
                        to="data_food_consortium.enterprise",
                    ),
                ),
            ],
            options={
                "rdf_type": "dfc-b:Coordination",
                "serializer_fields": [
                    "@id",
                    "name",
                    "enterprise",
                    "margin_percent",
                    "sale_sessions",
                ],
                "nested_fields": ["sale_sessions"],
            },
        ),
        migrations.CreateModel(
            name="PhysicalPlace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_server_source",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The URL of the dataserver which provided the instance",
                        null=True,
                    ),
                ),
                ("proxy_of", djangoldp.fields.LDPUrlField(blank=True, null=True)),
                ("phone_number", djangoldp.fields.TextField(blank=True, null=True)),
                ("URL", djangoldp.fields.TextField(blank=True, null=True)),
            ],
            options={
                "rdf_type": "dfc-b:PhysicalPlace",
                "serializer_fields": ["address", "main_contact", "phone_number", "URL"],
            },
        ),
        migrations.CreateModel(
            name="PhysicalPlaceAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_server_source",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The URL of the dataserver which provided the instance",
                        null=True,
                    ),
                ),
                ("proxy_of", djangoldp.fields.LDPUrlField(blank=True, null=True)),
                ("city", djangoldp.fields.TextField(blank=True, null=True)),
                ("country", djangoldp.fields.TextField(blank=True, null=True)),
                ("latitude", djangoldp.fields.TextField(blank=True, null=True)),
                ("longitude", djangoldp.fields.TextField(blank=True, null=True)),
                ("postcode", djangoldp.fields.TextField(blank=True, null=True)),
                ("region", djangoldp.fields.TextField(blank=True, null=True)),
                ("street", djangoldp.fields.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "default_permissions": {"delete", "add", "change", "view", "control"},
                "rdf_type": "dfc-b:Address",
                "serializer_fields": [
                    "@id",
                    "city",
                    "country",
                    "latitude",
                    "longitude",
                    "postcode",
                    "region",
                    "street",
                    "places",
                ],
                "nested_fields": ["places"],
                "depth": 0,
            },
        ),
        migrations.CreateModel(
            name="SaleSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_server_source",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The URL of the dataserver which provided the instance",
                        null=True,
                    ),
                ),
                ("proxy_of", djangoldp.fields.LDPUrlField(blank=True, null=True)),
                ("quantity", djangoldp.fields.FloatField(blank=True, null=True)),
                ("start_date", djangoldp.fields.DateTimeField(blank=True, null=True)),
                ("end_date", djangoldp.fields.DateTimeField(blank=True, null=True)),
                (
                    "coordination",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        help_text="The Coordination (that defines which Enterprise coordinates the Sales Sesison)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_sessions",
                        to="data_food_consortium.coordination",
                    ),
                ),
                (
                    "hosted_at",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_sessions",
                        to="data_food_consortium.physicalplace",
                    ),
                ),
            ],
            options={
                "rdf_type": "dfc-b:SaleSession",
                "serializer_fields": [
                    "@id",
                    "coordination",
                    "start_date",
                    "end_date",
                    "quantity",
                    "hosted_at",
                    "shipping_options",
                ],
                "nested_fields": ["shipping_options"],
            },
        ),
        migrations.CreateModel(
            name="ShippingOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_server_source",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The URL of the dataserver which provided the instance",
                        null=True,
                    ),
                ),
                ("proxy_of", djangoldp.fields.LDPUrlField(blank=True, null=True)),
                (
                    "has_type",
                    djangoldp.fields.CharField(
                        blank=True,
                        choices=[
                            (
                                "https://raw.githubusercontent.com/datafoodconsortium/ontology/refs/heads/master/src/DFC_BusinessOntology.owl#PickupOption",
                                "Pick-up",
                            ),
                            (
                                "https://raw.githubusercontent.com/datafoodconsortium/ontology/refs/heads/master/src/DFC_BusinessOntology.owl#DeliveryOption",
                                "Delivery",
                            ),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("fee", djangoldp.fields.FloatField(blank=True, null=True)),
                ("quantity", djangoldp.fields.FloatField(blank=True, null=True)),
                ("start_date", djangoldp.fields.DateTimeField(blank=True, null=True)),
                ("end_date", djangoldp.fields.DateTimeField(blank=True, null=True)),
                (
                    "delivers_at",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="data_food_consortium.physicalplace",
                    ),
                ),
                (
                    "picked_up_at",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collections",
                        to="data_food_consortium.physicalplace",
                    ),
                ),
                (
                    "sale_session",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_options",
                        to="data_food_consortium.salesession",
                    ),
                ),
            ],
            options={
                "rdf_type": "dfc-b:ShippingOption",
                "serializer_fields": [
                    "@id",
                    "has_type",
                    "fee",
                    "quantity",
                    "start_date",
                    "end_date",
                    "shipping_options",
                    "delivers_at",
                    "picked_up_at",
                    "sale_session",
                ],
            },
        ),
        migrations.AddField(
            model_name="physicalplace",
            name="address",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to="data_food_consortium.physicalplaceaddress",
            ),
        ),
        migrations.AddField(
            model_name="physicalplace",
            name="main_contact",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to="data_food_consortium.person",
            ),
        ),
    ]
