# Generated by Django 4.2.20 on 2025-08-26 15:26

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_food_consortium",
            "0017_coordination_physicalplace_physicalplaceaddress_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalplace",
            name="name",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
    ]
