# Generated by Django 4.2.20 on 2025-08-26 18:27

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0018_physicalplace_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customercategory",
            name="name",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
    ]
