# Generated by Django 4.2.20 on 2025-09-22 20:13

from django.db import migrations
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0019_customercategory_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingoption",
            name="enterprise",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="Automatically set to the enterprise coordinating the SaleSession. Not part of the DFC standard",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_options",
                to="data_food_consortium.enterprise",
            ),
        ),
    ]
