# Generated by Django 4.2.20 on 2025-09-25 09:30

from django.db import migrations
import django.db.models.deletion
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0020_shippingoption_enterprise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogitem",
            name="managed_by",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_items",
                to="data_food_consortium.enterprise",
            ),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="references",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referenced_by",
                to="data_food_consortium.suppliedproduct",
            ),
        ),
    ]
