# Generated by Django 4.2.20 on 2025-10-01 11:21

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0021_alter_catalogitem_managed_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="logo",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="logo_url",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="promo_image_url",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="logo",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="logo_url",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="promo_image_url",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
    ]
