# Generated by Django 4.2.20 on 2025-10-29 14:39

from django.db import migrations, models
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0023_alter_catalogitem_proxy_of_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceImportRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("import_started_at", models.DateTimeField()),
                (
                    "data_batches",
                    djangoldp.fields.JSONField(
                        blank=True,
                        help_text="A list of the JSON data received from the data-server, received in batches",
                        null=True,
                    ),
                ),
                (
                    "data_server_source",
                    djangoldp.fields.TextField(blank=True, null=True),
                ),
                (
                    "imported_models",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The models which were imported based on the webhook data",
                        null=True,
                    ),
                ),
                (
                    "imported_subjects",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The instances found in the data",
                        null=True,
                    ),
                ),
                (
                    "deleted_subjects",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="Instances which were discarded as a result of the import, e.g. if permission was removed",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
