# Generated by Django 4.2.20 on 2025-10-29 15:31

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0024_resourceimportrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceimportrecord",
            name="source",
            field=djangoldp.fields.CharField(
                blank=True,
                choices=[
                    ("admin_site", "Admin site"),
                    ("command_line", "Command line"),
                    ("update_webhook", "Update webhook event"),
                    ("refresh_webhook", "Refresh webhook event"),
                ],
                help_text="How the import was triggered (e.g. via the command line or webhook)",
                max_length=64,
                null=True,
            ),
        ),
    ]
