# Generated by Django 4.2.20 on 2025-10-29 15:58

from django.db import migrations, models
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0025_resourceimportrecord_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevokeWebhookRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data",
                    djangoldp.fields.JSONField(
                        blank=True,
                        help_text="The JSON data sent with the webhook",
                        null=True,
                    ),
                ),
                (
                    "platform_urlid",
                    djangoldp.fields.TextField(
                        blank=True,
                        help_text="The platform which sent the webhook",
                        null=True,
                    ),
                ),
                (
                    "source",
                    djangoldp.fields.CharField(
                        blank=True,
                        choices=[
                            ("admin_site", "Admin site"),
                            ("dataserver", "Received from dataserver"),
                        ],
                        help_text="How the webhook was triggered",
                        max_length=64,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
