# Generated by Django 4.2.20 on 2025-11-14 11:38

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0026_revokewebhookrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogitem",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coordination",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customercategory",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enterpriseaddress",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enterpriseservice",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="localizedproduct",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="physicalplace",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="physicalplaceaddress",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="price",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salesession",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shippingoption",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="suppliedproduct",
            name="proxy_of",
            field=djangoldp.fields.TextField(blank=True, null=True),
        ),
    ]
