# Generated by Django 5.2.16 on 2026-07-21 20:42

import djangoldp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0027_alter_catalogitem_proxy_of_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliedproduct",
            name="has_type",
            field=djangoldp.fields.CharField(
                blank=True,
                choices=[
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#alcoholic-beverage",
                        "Alcoholic beverage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#alcoholicbeverage",
                        "Alcoholicbeverage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#almond",
                        "Almond",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#aperitif",
                        "Aperitif",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#apples",
                        "Apples",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#apricot",
                        "Apricot",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#artichoke",
                        "Artichoke",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#asparagus",
                        "Asparagus",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#bakery",
                        "Bakery",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#basil", "Basil"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#bean", "Bean"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#beans", "Beans"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#beef", "Beef"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#beer", "Beer"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#beetroot",
                        "Beetroot",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#berry", "Berry"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#biscuit",
                        "Biscuit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#blackberry",
                        "Blackberry",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#blackcurrant",
                        "Blackcurrant",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#blueberry",
                        "Blueberry",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#bluefoot-mushroom",
                        "Bluefoot mushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#bluefootmushroom",
                        "Bluefootmushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#bottled-fruit",
                        "Bottled fruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#bottled-vegetable",
                        "Bottled vegetable",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#bottledfruit",
                        "Bottledfruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#bottledvegetable",
                        "Bottledvegetable",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#bread", "Bread"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#broccoli-cabbage",
                        "Broccoli cabbage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#broccolicabbage",
                        "Broccolicabbage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#brussels-sprouts",
                        "Brussels sprouts",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#brusselssprouts",
                        "Brusselssprouts",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#butter",
                        "Butter",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#butternut",
                        "Butternut",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cabbage",
                        "Cabbage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#canned-fruit",
                        "Canned fruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#canned-vegetable",
                        "Canned vegetable",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cannedfruit",
                        "Cannedfruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cannedgoods",
                        "Cannedgoods",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cannedvegetable",
                        "Cannedvegetable",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#carrot",
                        "Carrot",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cauliflower",
                        "Cauliflower",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#celeriac",
                        "Celeriac",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#celery-branch",
                        "Celery branch",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#celerybranch",
                        "Celerybranch",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#chanterelle-mushroom",
                        "Chanterelle mushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#chanterellemushroom",
                        "Chanterellemushroom",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#chard", "Chard"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cherry",
                        "Cherry",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cherry-tomato",
                        "Cherry tomato",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cherrytomato",
                        "Cherrytomato",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#chervil",
                        "Chervil",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#chestnut",
                        "Chestnut",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#chicken",
                        "Chicken",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#chicory",
                        "Chicory",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#chilli-pepper",
                        "Chilli pepper",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#chillipepper",
                        "Chillipepper",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#chinese-cabbage",
                        "Chinese cabbage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#chinesecabbage",
                        "Chinesecabbage",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#chive", "Chive"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#cider", "Cider"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#clementine",
                        "Clementine",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cluster-tomato",
                        "Cluster tomato",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#clustertomato",
                        "Clustertomato",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#confectionery",
                        "Confectionery",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cooked-meat",
                        "Cooked meat",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cookedmeat",
                        "Cookedmeat",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#coriander",
                        "Coriander",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#corn-salad",
                        "Corn salad",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cornsalad",
                        "Cornsalad",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cosmetic",
                        "Cosmetic",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#coulemelle-mushroom",
                        "Coulemelle mushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#coulemellemushroom",
                        "Coulemellemushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#courgette",
                        "Courgette",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cow-dairy-product",
                        "Cow dairy product",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cowdairyproduct",
                        "Cowdairyproduct",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cream-cheese",
                        "Cream cheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#creamcheese",
                        "Creamcheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#crepe-and-galette",
                        "Crepe and galette",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#crepeandgalette",
                        "Crepeandgalette",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#cress", "Cress"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#cucumber",
                        "Cucumber",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#currant",
                        "Currant",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#dairy-dessert",
                        "Dairy dessert",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#dairy-product",
                        "Dairy product",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#dairydessert",
                        "Dairydessert",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#dairyproduct",
                        "Dairyproduct",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#dandelion",
                        "Dandelion",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#deaths-trumpet",
                        "Deaths trumpet",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#deathstrumpet",
                        "Deathstrumpet",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#delicatessen",
                        "Delicatessen",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#digestive",
                        "Digestive",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#dill", "Dill"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#dried-fruit",
                        "Dried fruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#dried-vegetable",
                        "Dried vegetable",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#dried_goods",
                        "Dried_goods",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#dried_herb",
                        "Dried_herb",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#driedfruit",
                        "Driedfruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#driedgoods",
                        "Driedgoods",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#driedherb",
                        "Driedherb",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#driedvegetable",
                        "Driedvegetable",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#drink", "Drink"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#duck", "Duck"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#egg", "Egg"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#eggplant",
                        "Eggplant",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#endive",
                        "Endive",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fennel",
                        "Fennel",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#ferment",
                        "Ferment",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#festive-poultry",
                        "Festive poultry",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#festivepoultry",
                        "Festivepoultry",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fifth-range-vegetable",
                        "Fifth range vegetable",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fifthrangevegetable",
                        "Fifthrangevegetable",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#fig", "Fig"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#fish", "Fish"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fishery-product",
                        "Fishery product",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fisheryproduct",
                        "Fisheryproduct",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#flake", "Flake"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#flavored-yogurt",
                        "Flavored yogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#flavoredyogurt",
                        "Flavoredyogurt",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#flour", "Flour"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#flower",
                        "Flower",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fourth-range-vegetable",
                        "Fourth range vegetable",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fourthrangevegetable",
                        "Fourthrangevegetable",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fresh-cheese",
                        "Fresh cheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fresh-cream",
                        "Fresh cream",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fresh-meat",
                        "Fresh meat",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#freshcheese",
                        "Freshcheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#freshcream",
                        "Freshcream",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#freshmeat",
                        "Freshmeat",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#frozen",
                        "Frozen",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#frozen-fruit",
                        "Frozen fruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#frozen-meal",
                        "Frozen meal",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#frozen-meat",
                        "Frozen meat",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#frozen-vegetable",
                        "Frozen vegetable",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#frozenfruit",
                        "Frozenfruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#frozenmeal",
                        "Frozenmeal",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#frozenmeat",
                        "Frozenmeat",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#frozenvegetable",
                        "Frozenvegetable",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#fruit", "Fruit"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fruit-in-compote",
                        "Fruit in compote",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fruit-juice",
                        "Fruit juice",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fruitincompote",
                        "Fruitincompote",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#fruitjuice",
                        "Fruitjuice",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#garlic",
                        "Garlic",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#girolle-mushroom",
                        "Girolle mushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#girollemushroom",
                        "Girollemushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goat-dairy-dessert",
                        "Goat dairy dessert",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goat-dairy-product",
                        "Goat dairy product",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goat-flavored-yogurt",
                        "Goat flavored yogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goat-fresh-cheese",
                        "Goat fresh cheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goat-mature-cheese",
                        "Goat mature cheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goat-milk",
                        "Goat milk",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goat-natural-yogurt",
                        "Goat natural yogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goat-sweet-yogurt",
                        "Goat sweet yogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goat-yogurt-on-a-bed-of-fruit",
                        "Goat yogurt on a bed of fruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goat-yogurt-with-fruits",
                        "Goat yogurt with fruits",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goatdairydessert",
                        "Goatdairydessert",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goatdairyproduct",
                        "Goatdairyproduct",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goatflavoredyogurt",
                        "Goatflavoredyogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goatfreshcheese",
                        "Goatfreshcheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goatmaturecheese",
                        "Goatmaturecheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goatmilk",
                        "Goatmilk",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goatnaturalyogurt",
                        "Goatnaturalyogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goatsweetyogurt",
                        "Goatsweetyogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goatyogurtonabedoffruit",
                        "Goatyogurtonabedoffruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#goatyogurtwithfruits",
                        "Goatyogurtwithfruits",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#goose", "Goose"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#gooseberry",
                        "Gooseberry",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#grain", "Grain"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#grape", "Grape"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#green-garlic",
                        "Green garlic",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#greengarlic",
                        "Greengarlic",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#grilling-meat",
                        "Grilling meat",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#grillingmeat",
                        "Grillingmeat",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#guinea-fowl",
                        "Guinea fowl",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#guineafowl",
                        "Guineafowl",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#hazelnut",
                        "Hazelnut",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#herb", "Herb"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#hierloom-squash",
                        "Hierloom squash",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#hierloom-tomato",
                        "Hierloom tomato",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#hierloomsquash",
                        "Hierloomsquash",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#hierloomtomato",
                        "Hierloomtomato",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#honey", "Honey"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#inedible",
                        "Inedible",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#jam", "Jam"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#jerusalem-artichoke",
                        "Jerusalem artichoke",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#jerusalemartichoke",
                        "Jerusalemartichoke",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#kale", "Kale"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#kale-cabbage",
                        "Kale cabbage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#kalecabbage",
                        "Kalecabbage",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#kiwi", "Kiwi"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#kohlrabi",
                        "Kohlrabi",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#lamb", "Lamb"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#laurel",
                        "Laurel",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#leek", "Leek"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#lemon", "Lemon"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#lemonade",
                        "Lemonade",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#lentils",
                        "Lentils",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#lettuce",
                        "Lettuce",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#local-grocery-store",
                        "Local grocery store",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#localgrocerystore",
                        "Localgrocerystore",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#mandarin",
                        "Mandarin",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#mature-cheese",
                        "Mature cheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#maturecheese",
                        "Maturecheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#meat-product",
                        "Meat product",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#meatproduct",
                        "Meatproduct",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#medlar",
                        "Medlar",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#melon", "Melon"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#mesclun",
                        "Mesclun",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#milk", "Milk"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#milky-mushroom",
                        "Milky mushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#milkymushroom",
                        "Milkymushroom",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#mint", "Mint"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#morel", "Morel"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#mousseron",
                        "Mousseron",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#mushroom",
                        "Mushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#natural-yogurt",
                        "Natural yogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#naturalyogurt",
                        "Naturalyogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#nectarine",
                        "Nectarine",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#non-local-fruit",
                        "Non local fruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#non-local-vegetable",
                        "Non local vegetable",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#nonlocalfruit",
                        "Nonlocalfruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#nonlocalvegetable",
                        "Nonlocalvegetable",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#nut", "Nut"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#oil", "Oil"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#onion", "Onion"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#orange",
                        "Orange",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#other-cheese",
                        "Other cheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#other-dairy-product",
                        "Other dairy product",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#other-milk",
                        "Other milk",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#othercheese",
                        "Othercheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#otherdairyproduct",
                        "Otherdairyproduct",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#othermilk",
                        "Othermilk",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#oyster-mushroom",
                        "Oyster mushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#oystermushroom",
                        "Oystermushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#paris-mushroom",
                        "Paris mushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#parismushroom",
                        "Parismushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#parsley",
                        "Parsley",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#parsnip",
                        "Parsnip",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#pasta", "Pasta"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#pastry",
                        "Pastry",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#pattypan-squash",
                        "Pattypan squash",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#pattypansquash",
                        "Pattypansquash",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#peach", "Peach"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#pear", "Pear"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#peas", "Peas"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#pepper",
                        "Pepper",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#pie-pastry",
                        "Pie pastry",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#piepastry",
                        "Piepastry",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#pigeon",
                        "Pigeon",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#plant", "Plant"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#plum", "Plum"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#porcini",
                        "Porcini",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#pork", "Pork"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#potato",
                        "Potato",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#poultry",
                        "Poultry",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#processed-fruit",
                        "Processed fruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#processed-vegetable",
                        "Processed vegetable",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#processedfruit",
                        "Processedfruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#processedvegetable",
                        "Processedvegetable",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#prune", "Prune"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#pulse", "Pulse"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#pumpkin",
                        "Pumpkin",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#purslane",
                        "Purslane",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#quail", "Quail"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#quince",
                        "Quince",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#quinoa",
                        "Quinoa",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#rabbit",
                        "Rabbit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#radish",
                        "Radish",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#raspberry",
                        "Raspberry",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#ready-meal",
                        "Ready meal",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#readymeal",
                        "Readymeal",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#red-cabbage",
                        "Red cabbage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#redcabbage",
                        "Redcabbage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#rhubarb",
                        "Rhubarb",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#rice", "Rice"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#rocket",
                        "Rocket",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#romanesco",
                        "Romanesco",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#rosemary",
                        "Rosemary",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#round-tomato",
                        "Round tomato",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#roundtomato",
                        "Roundtomato",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#rutabaga",
                        "Rutabaga",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#sage", "Sage"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#salad", "Salad"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#salad-mix",
                        "Salad mix",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#saladmix",
                        "Saladmix",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#salsify",
                        "Salsify",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#salt", "Salt"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#salting",
                        "Salting",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#savory-groceries",
                        "Savory groceries",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#savorygroceries",
                        "Savorygroceries",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#savoy-cabbage",
                        "Savoy cabbage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#savoycabbage",
                        "Savoycabbage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#seashell",
                        "Seashell",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#seed", "Seed"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#semolina",
                        "Semolina",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#shallot",
                        "Shallot",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheep-dairy-dessert",
                        "Sheep dairy dessert",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheep-dairy-product",
                        "Sheep dairy product",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheep-flavored-yogurt",
                        "Sheep flavored yogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheep-fresh-cheese",
                        "Sheep fresh cheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheep-mature-cheese",
                        "Sheep mature cheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheep-milk",
                        "Sheep milk",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheep-natural-yogurt",
                        "Sheep natural yogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheep-sweet-yogurt",
                        "Sheep sweet yogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheep-yogurt-on-a-bed-of-fruit",
                        "Sheep yogurt on a bed of fruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheep-yogurt-with-fruits",
                        "Sheep yogurt with fruits",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheepdairydessert",
                        "Sheepdairydessert",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheepdairyproduct",
                        "Sheepdairyproduct",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheepflavoredyogurt",
                        "Sheepflavoredyogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheepfoot-mushroom",
                        "Sheepfoot mushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheepfootmushroom",
                        "Sheepfootmushroom",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheepfreshcheese",
                        "Sheepfreshcheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheepmaturecheese",
                        "Sheepmaturecheese",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheepmilk",
                        "Sheepmilk",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheepnaturalyogurt",
                        "Sheepnaturalyogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheepsweetyogurt",
                        "Sheepsweetyogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheepyogurtonabedoffruit",
                        "Sheepyogurtonabedoffruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sheepyogurtwithfruits",
                        "Sheepyogurtwithfruits",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#shellfish",
                        "Shellfish",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#simmering-meat",
                        "Simmering meat",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#simmeringmeat",
                        "Simmeringmeat",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#smooth-cabbage",
                        "Smooth cabbage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#smoothcabbage",
                        "Smoothcabbage",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#smoothie",
                        "Smoothie",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#snack", "Snack"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#snails",
                        "Snails",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#soft-drink",
                        "Soft drink",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#softdrink",
                        "Softdrink",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#soup", "Soup"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#spinach",
                        "Spinach",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#squash",
                        "Squash",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#strawberry",
                        "Strawberry",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sweet-groceries",
                        "Sweet groceries",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sweet-yogurt",
                        "Sweet yogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sweetgroceries",
                        "Sweetgroceries",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#sweetyogurt",
                        "Sweetyogurt",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#tarragon",
                        "Tarragon",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#thyme", "Thyme"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#tomato",
                        "Tomato",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#truffle",
                        "Truffle",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#turkey",
                        "Turkey",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#turnip",
                        "Turnip",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#uchiki-kuri-squash",
                        "Uchiki kuri squash",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#uchikikurisquash",
                        "Uchikikurisquash",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#veal", "Veal"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#vegetable",
                        "Vegetable",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#venison",
                        "Venison",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#viennoiserie",
                        "Viennoiserie",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#viennoiserie-",
                        "Viennoiserie ",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#walnut",
                        "Walnut",
                    ),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#wine", "Wine"),
                    ("https://w3id.org/dfc/taxonomies/productTypes.rdf#yam", "Yam"),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#yogurt-on-a-bed-of-fruit",
                        "Yogurt on a bed of fruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#yogurt-with-fruits",
                        "Yogurt with fruits",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#yogurtonabedoffruit",
                        "Yogurtonabedoffruit",
                    ),
                    (
                        "https://w3id.org/dfc/taxonomies/productTypes.rdf#yogurtwithfruits",
                        "Yogurtwithfruits",
                    ),
                ],
                max_length=255,
                null=True,
                verbose_name="has_type",
            ),
        ),
    ]
