# Generated by Django 5.2.16 on 2026-08-04 08:18

import django.db.models.deletion
import djangoldp.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0028_alter_suppliedproduct_has_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataServer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="coordination",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="customercategory",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="enterpriseaddress",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="enterpriseservice",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="localizedproduct",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="physicalplace",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="physicalplaceaddress",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="salesession",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="shippingoption",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AddField(
            model_name="suppliedproduct",
            name="data_server_source_new",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="data_food_consortium.dataserver",
            ),
        ),
    ]
