# Generated by Django 5.2.16 on 2026-08-04 09:41

import django.db.models.deletion
import djangoldp.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0030_populate_dataserver_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssignedScope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    djangoldp.fields.CharField(
                        blank=True,
                        choices=[
                            (
                                "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/scopes.rdf#ReadProducts",
                                "ReadProducts",
                            ),
                            (
                                "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/scopes.rdf#WriteProducts",
                                "WriteProducts",
                            ),
                            (
                                "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/scopes.rdf#ReadOrders",
                                "ReadOrders",
                            ),
                            (
                                "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/scopes.rdf#WriteOrders",
                                "WriteOrders",
                            ),
                            (
                                "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/scopes.rdf#ReadEnterprise",
                                "ReadEnterprise",
                            ),
                            (
                                "https://github.com/datafoodconsortium/taxonomies/releases/latest/download/scopes.rdf#WriteEnterprise",
                                "WriteEnterprise",
                            ),
                        ],
                        default="https://github.com/datafoodconsortium/taxonomies/releases/latest/download/scopes.rdf#ReadProducts",
                        help_text="The scope assigned, a permission granted (absence of scope implicitly means absence of permission)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "data_server",
                    djangoldp.fields.ForeignKey(
                        help_text="The enterprise (producer) which granted and controls the scope",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_scopes",
                        to="data_food_consortium.dataserver",
                    ),
                ),
                (
                    "platform",
                    djangoldp.fields.ForeignKey(
                        help_text="The platform the scope is assigned to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_scopes",
                        to="data_food_consortium.platform",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": {"add", "change", "control", "delete", "view"},
                "depth": 0,
            },
        ),
    ]
