from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("data_food_consortium", "0031_platform_assignedscope")]

    operations = [
        migrations.RemoveField(
            model_name="catalogitem",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="coordination",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="customercategory",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="enterpriseaddress",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="enterpriseservice",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="localizedproduct",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="person",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="physicalplace",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="physicalplaceaddress",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="price",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="salesession",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="service",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="shippingoption",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="socialmedia",
            name="data_server_source",
        ),
        migrations.RemoveField(
            model_name="suppliedproduct",
            name="data_server_source",
        ),
        migrations.RenameField(
            model_name="catalogitem",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="coordination",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="customercategory",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="enterprise",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="enterpriseaddress",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="enterpriseservice",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="localizedproduct",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="offer",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="physicalplace",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="physicalplaceaddress",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="price",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="salesession",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="shippingoption",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="socialmedia",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
        migrations.RenameField(
            model_name="suppliedproduct",
            old_name="data_server_source_new",
            new_name="data_server_source",
        ),
    ]
