# Generated by Django 5.2.16 on 2026-08-18 09:50

import django.db.models.deletion
import djangoldp.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0032_swap_data_server_source_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedscope",
            name="user",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="A scope can be assigned to an individual user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_scopes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assignedscope",
            name="platform",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="A scope can be assigned to a platform, and all of its members",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_scopes",
                to="data_food_consortium.platform",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignedscope",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("platform__isnull", False), ("user__isnull", True)),
                    models.Q(("platform__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="assigned_to_exactly_one_object",
            ),
        ),
    ]
