# Generated by Django 5.2.16 on 2026-09-04 15:51

import django.db.models.deletion
import djangoldp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_food_consortium",
            "0033_assignedscope_user_alter_assignedscope_platform_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogitem",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="coordination",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="customercategory",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="enterpriseaddress",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="enterpriseservice",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="localizedproduct",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="physicalplace",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="physicalplaceaddress",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="salesession",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="shippingoption",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
        migrations.AlterField(
            model_name="suppliedproduct",
            name="data_server_source",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The dataserver which provided the instance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_food_consortium.dataserver",
            ),
        ),
    ]
