# Generated by Django 5.2.16 on 2026-09-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0034_alter_catalogitem_data_server_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceimportrecord",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourceimportrecord",
            name="error_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auth_err", "Authentication Error"),
                    ("request_err", "Network Error"),
                    ("parse_err", "Parse Error"),
                    ("other_err", "Other"),
                ],
                help_text="Null if there was no failure; otherwise, the category of failure",
                max_length=64,
                null=True,
            ),
        ),
    ]
