# Generated by Django 5.2.16 on 2026-09-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0035_resourceimportrecord_error_message_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="revokewebhookrecord",
            old_name="platform_urlid",
            new_name="data_server_urlid",
        ),
    ]
