# Generated by Django 5.2.16 on 2026-10-01 14:57

import django.db.models.deletion
import djangoldp.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0037_revokewebhookrecord_data_server"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrantWebhookRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data",
                    djangoldp.fields.JSONField(
                        blank=True,
                        help_text="The JSON data sent with the webhook",
                        null=True,
                    ),
                ),
                (
                    "source",
                    djangoldp.fields.CharField(
                        blank=True,
                        choices=[
                            ("admin_site", "Admin site"),
                            ("dataserver", "Received from dataserver"),
                        ],
                        help_text="How the webhook was triggered",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "data_server",
                    djangoldp.fields.ForeignKey(
                        help_text="The data server which sent the webhook",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_food_consortium.dataserver",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
