# Generated by Django 5.2.16 on 2026-10-01 17:03

import djangoldp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0038_grantwebhookrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedscope",
            name="proxied_obj_urlid",
            field=djangoldp.fields.TextField(
                default="all",
                help_text="The urlid of the object upon which the scope is granted",
            ),
            preserve_default=False,
        ),
    ]
