# Generated by Django 5.2.16 on 2026-10-01 17:24

import djangoldp.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0039_assignedscope_proxied_obj_urlid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assignedscope",
            name="assigned_to_exactly_one_object",
        ),
        migrations.AlterField(
            model_name="assignedscope",
            name="proxied_obj_urlid",
            field=djangoldp.fields.TextField(
                help_text="The urlid of the object upon which the scope is granted. Set to 'all', the user can access all objects"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignedscope",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("platform__isnull", False), ("user__isnull", True)),
                    models.Q(("platform__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="assigned_to_exactly_one_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignedscope",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("proxied_obj_urlid__isnull", True),
                    ("proxied_obj_urlid", ""),
                    _connector="OR",
                    _negated=True,
                ),
                name="assigned_to_object",
            ),
        ),
    ]
