# Generated by Django 5.2.16 on 2026-10-04 11:19

import django.db.models.deletion
import djangoldp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_food_consortium",
            "0040_remove_assignedscope_assigned_to_exactly_one_object_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(old_name="Enterprise", new_name="Organization"),
        migrations.RenameModel(
            old_name="EnterpriseAddress",
            new_name="OrganizationAddress",
        ),
        migrations.RenameModel(
            old_name="EnterpriseService", new_name="OrganizationService"
        ),
        migrations.RenameField(
            model_name="socialmedia",
            old_name="enterprise",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="organizationservice",
            old_name="enterprise",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="coordination",
            old_name="enterprise",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="shippingoption",
            old_name="enterprise",
            new_name="organization",
        ),
        migrations.AlterField(
            model_name="organization",
            name="VATnumber",
            field=djangoldp.fields.TextField(
                blank=True,
                help_text="Any Tax Registration Number that is applicable to the entity, in the jurisdiction the entity is operating in.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="VATstatus",
            field=djangoldp.fields.BooleanField(
                default=False,
                help_text="Indicates whether the entity charges VAT or not",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coordination",
            name="organization",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="Confirms the entity Coordinates certain SaleSessions, and defines margin percentage that the entity takes for managing the SaleSession",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordinations",
                to="data_food_consortium.organization",
            ),
        ),
        migrations.AlterField(
            model_name="coordination",
            name="margin_percent",
            field=djangoldp.fields.FloatField(
                blank=True,
                default=0.0,
                help_text="The percentage margin the coordinating entity is charging as comission for managing the Sales Session (from 0-100)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesession",
            name="coordination",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="The Coordination (that defines which Organization coordinates the Sales Sesison)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_sessions",
                to="data_food_consortium.coordination",
            ),
        ),
        migrations.AlterField(
            model_name="shippingoption",
            name="organization",
            field=djangoldp.fields.ForeignKey(
                blank=True,
                help_text="Automatically set to the entity coordinating the SaleSession. Not part of the DFC standard",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_options",
                to="data_food_consortium.organization",
            ),
        ),
        migrations.AlterField(
            model_name="assignedscope",
            name="data_server",
            field=djangoldp.fields.ForeignKey(
                help_text="The organization (producer) which granted and controls the scope",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="granted_scopes",
                to="data_food_consortium.dataserver",
            ),
        ),
    ]
