# Generated by Django 5.2.16 on 2026-10-04 18:08

import django.db.models.deletion
import djangoldp.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0041_rename_enterprise_to_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateSaleSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urlid",
                    djangoldp.fields.LDPUrlField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "is_backlink",
                    models.BooleanField(
                        default=False,
                        help_text="set automatically to indicate the Model is a backlink",
                    ),
                ),
                (
                    "allow_create_backlink",
                    models.BooleanField(
                        default=True,
                        help_text="set to False to disable backlink creation after Model save",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("proxy_of", djangoldp.fields.TextField(blank=True, null=True)),
                (
                    "data_server_source",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        help_text="The dataserver which provided the instance",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_food_consortium.dataserver",
                    ),
                ),
                (
                    "hosted_at",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_sale_sessions",
                        to="data_food_consortium.physicalplace",
                    ),
                ),
                (
                    "organization",
                    djangoldp.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_sale_sessions",
                        to="data_food_consortium.organization",
                    ),
                ),
            ],
            options={
                "rdf_type": "dfc-b:TemplateSaleSession",
                "serializer_fields": ["@id", "proxy_of", "data_server_source"],
            },
        ),
    ]
