# Generated by Django 5.2.16 on 2026-10-10 10:23

import djangoldp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_food_consortium", "0042_templatesalesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitem",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coordination",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customercategory",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="localizedproduct",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationaddress",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationservice",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="physicalplace",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="physicalplaceaddress",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="salesession",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shippingoption",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="suppliedproduct",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="templatesalesession",
            name="additional",
            field=djangoldp.fields.JSONField(
                blank=True,
                help_text="DjangoLDP will serialize any data included here as though they are part of the instance, omitting the additional field",
                null=True,
            ),
        ),
    ]
